services:
  - docker
notifications:
  email: false
dist: xenial
language: cpp
os: linux
compiler:
- clang
cache: ccache
before_install:
  - docker pull doscode/merger-build-env:latest
  - docker run -d --name build-env --rm -i -t doscode/merger-build-env:latest bash
install:
script:
  - docker exec build-env sh -c "
    mkdir -p workspace && cd workspace;
    git clone --depth=50 --branch=$TRAVIS_BRANCH https://github.com/gruut/tethys-utils.git && cd tethys-utils;
    mkdir -p build && cd build;
    cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DCMAKE_CXX_COMPILER="clang++" ..
    "
  - docker exec build-env sh -c "
    cd workspace/tethys-utils/build/;
    cp ../scripts/run-clang-tidy.py run-clang-tidy.py;
    python3 run-clang-tidy.py;
    "
  - docker exec build-env sh -c "
    cd workspace/tethys-utils/build;
    cmake --build . -j 4;
    ./test/tethys_utils_test
    "
